.\vs_dist\Debug\Palmtree.Math.Test_x86.exe
REM PAUSE
.\vs_dist\Debug\Palmtree.Math.Test_x64.exe
REM PAUSE
.\dist\Debug\Palmtree.Math.Test_x86.exe
REM PAUSE
.\dist\Debug\Palmtree.Math.Test_x64.exe
REM PAUSE
.\vs_dist\Release\Palmtree.Math.Test_x86.exe
REM PAUSE
.\vs_dist\Release\Palmtree.Math.Test_x64.exe
REM PAUSE
.\dist\Release\Palmtree.Math.Test_x86.exe
REM PAUSE
.\dist\Release\Palmtree.Math.Test_x64.exe
